// Generated by gencpp from file warthog_msgs/Status.msg
// DO NOT EDIT!


#ifndef WARTHOG_MSGS_MESSAGE_STATUS_H
#define WARTHOG_MSGS_MESSAGE_STATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace warthog_msgs
{
template <class ContainerAllocator>
struct Status_
{
  typedef Status_<ContainerAllocator> Type;

  Status_()
    : header()
    , hardware_id()
    , mcu_uptime()
    , connection_uptime()
    , mcu_temperature(0.0)
    , stop_engaged(false)
    , measured_battery(0.0)
    , measured_48v(0.0)
    , measured_24v(0.0)
    , measured_12v(0.0)
    , current_battery(0.0)
    , current_48v(0.0)
    , current_24v(0.0)
    , current_12v(0.0)
    , current_computer(0.0)
    , current_battery_peak(0.0)
    , total_power_consumed(0.0)  {
    }
  Status_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , hardware_id(_alloc)
    , mcu_uptime()
    , connection_uptime()
    , mcu_temperature(0.0)
    , stop_engaged(false)
    , measured_battery(0.0)
    , measured_48v(0.0)
    , measured_24v(0.0)
    , measured_12v(0.0)
    , current_battery(0.0)
    , current_48v(0.0)
    , current_24v(0.0)
    , current_12v(0.0)
    , current_computer(0.0)
    , current_battery_peak(0.0)
    , total_power_consumed(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _hardware_id_type;
  _hardware_id_type hardware_id;

   typedef ros::Duration _mcu_uptime_type;
  _mcu_uptime_type mcu_uptime;

   typedef ros::Duration _connection_uptime_type;
  _connection_uptime_type connection_uptime;

   typedef float _mcu_temperature_type;
  _mcu_temperature_type mcu_temperature;

   typedef uint8_t _stop_engaged_type;
  _stop_engaged_type stop_engaged;

   typedef float _measured_battery_type;
  _measured_battery_type measured_battery;

   typedef float _measured_48v_type;
  _measured_48v_type measured_48v;

   typedef float _measured_24v_type;
  _measured_24v_type measured_24v;

   typedef float _measured_12v_type;
  _measured_12v_type measured_12v;

   typedef float _current_battery_type;
  _current_battery_type current_battery;

   typedef float _current_48v_type;
  _current_48v_type current_48v;

   typedef float _current_24v_type;
  _current_24v_type current_24v;

   typedef float _current_12v_type;
  _current_12v_type current_12v;

   typedef float _current_computer_type;
  _current_computer_type current_computer;

   typedef float _current_battery_peak_type;
  _current_battery_peak_type current_battery_peak;

   typedef double _total_power_consumed_type;
  _total_power_consumed_type total_power_consumed;





  typedef boost::shared_ptr< ::warthog_msgs::Status_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::warthog_msgs::Status_<ContainerAllocator> const> ConstPtr;

}; // struct Status_

typedef ::warthog_msgs::Status_<std::allocator<void> > Status;

typedef boost::shared_ptr< ::warthog_msgs::Status > StatusPtr;
typedef boost::shared_ptr< ::warthog_msgs::Status const> StatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::warthog_msgs::Status_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::warthog_msgs::Status_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace warthog_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'warthog_msgs': ['/home/zeeshan/dewa_evaluation_zeeshan/p2_waypoint_nav/warthog_ws/src/warthog/warthog_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::warthog_msgs::Status_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::warthog_msgs::Status_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::warthog_msgs::Status_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::warthog_msgs::Status_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::warthog_msgs::Status_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::warthog_msgs::Status_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::warthog_msgs::Status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0da9e8a166e293e1a5dc327e76c16322";
  }

  static const char* value(const ::warthog_msgs::Status_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0da9e8a166e293e1ULL;
  static const uint64_t static_value2 = 0xa5dc327e76c16322ULL;
};

template<class ContainerAllocator>
struct DataType< ::warthog_msgs::Status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "warthog_msgs/Status";
  }

  static const char* value(const ::warthog_msgs::Status_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::warthog_msgs::Status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This message represents Warthog's lower-frequency status updates from the MCU\n\
# Default publish frequency is 1Hz.\n\
\n\
Header header\n\
\n\
# Commit of firmware source.\n\
string hardware_id\n\
\n\
# Times since MCU power-on and MCU rosserial connection, respectively.\n\
duration mcu_uptime\n\
duration connection_uptime\n\
\n\
# Temperature of MCU in Celsius.\n\
float32 mcu_temperature\n\
\n\
# Monitoring the run/stop loop. Changes in these values trigger an immediate\n\
# publish, outside the ordinarily-scheduled 1Hz updates.\n\
bool stop_engaged  # True when a stop has been pressed on the robot.\n\
\n\
# Voltage rails, in volts\n\
# Averaged over the message period\n\
float32 measured_battery\n\
float32 measured_48v\n\
float32 measured_24v\n\
float32 measured_12v\n\
\n\
# Current senses available on platform, in amps.\n\
# Averaged over the message period.\n\
float32 current_battery # This is total current being used from the battery which includes the items below and motors.\n\
float32 current_48v\n\
float32 current_24v\n\
float32 current_12v\n\
float32 current_computer\n\
\n\
# Highest total system current peak as measured in a 1ms window.\n\
float32 current_battery_peak\n\
\n\
# Integration of all power consumption since MCU power-on, in watt-hours.\n\
float64 total_power_consumed\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::warthog_msgs::Status_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::warthog_msgs::Status_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.hardware_id);
      stream.next(m.mcu_uptime);
      stream.next(m.connection_uptime);
      stream.next(m.mcu_temperature);
      stream.next(m.stop_engaged);
      stream.next(m.measured_battery);
      stream.next(m.measured_48v);
      stream.next(m.measured_24v);
      stream.next(m.measured_12v);
      stream.next(m.current_battery);
      stream.next(m.current_48v);
      stream.next(m.current_24v);
      stream.next(m.current_12v);
      stream.next(m.current_computer);
      stream.next(m.current_battery_peak);
      stream.next(m.total_power_consumed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Status_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::warthog_msgs::Status_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::warthog_msgs::Status_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "hardware_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.hardware_id);
    s << indent << "mcu_uptime: ";
    Printer<ros::Duration>::stream(s, indent + "  ", v.mcu_uptime);
    s << indent << "connection_uptime: ";
    Printer<ros::Duration>::stream(s, indent + "  ", v.connection_uptime);
    s << indent << "mcu_temperature: ";
    Printer<float>::stream(s, indent + "  ", v.mcu_temperature);
    s << indent << "stop_engaged: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.stop_engaged);
    s << indent << "measured_battery: ";
    Printer<float>::stream(s, indent + "  ", v.measured_battery);
    s << indent << "measured_48v: ";
    Printer<float>::stream(s, indent + "  ", v.measured_48v);
    s << indent << "measured_24v: ";
    Printer<float>::stream(s, indent + "  ", v.measured_24v);
    s << indent << "measured_12v: ";
    Printer<float>::stream(s, indent + "  ", v.measured_12v);
    s << indent << "current_battery: ";
    Printer<float>::stream(s, indent + "  ", v.current_battery);
    s << indent << "current_48v: ";
    Printer<float>::stream(s, indent + "  ", v.current_48v);
    s << indent << "current_24v: ";
    Printer<float>::stream(s, indent + "  ", v.current_24v);
    s << indent << "current_12v: ";
    Printer<float>::stream(s, indent + "  ", v.current_12v);
    s << indent << "current_computer: ";
    Printer<float>::stream(s, indent + "  ", v.current_computer);
    s << indent << "current_battery_peak: ";
    Printer<float>::stream(s, indent + "  ", v.current_battery_peak);
    s << indent << "total_power_consumed: ";
    Printer<double>::stream(s, indent + "  ", v.total_power_consumed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WARTHOG_MSGS_MESSAGE_STATUS_H
